# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='test',
            field=models.DateField(),
        ),
    ]
